fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    archive: "https://github.com/voxpupuli/puppet-archive.git"
    augeas_core: "https://github.com/puppetlabs/puppetlabs-augeas_core.git"
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent:
      repo: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
      ref: v4.21.0
    provision: 'https://github.com/puppetlabs/provision.git'

  symlinks:
    tomcat: "#{source_dir}"
