fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    staging: "https://github.com/voxpupuli/puppet-staging.git"
  symlinks:
    tomcat: "#{source_dir}"
