# only run a minimal subset of tests on travis, running all the tests can cause travis to timeout
.travis.yml:
  docker_sets:
  - set: docker/ubuntu-14.04
    options:
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=@@SET@@ SPEC_OPTS="--tag docker"
  - set: docker/centos-7
    options:
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=@@SET@@ SPEC_OPTS="--tag docker"
  includes:
  - rvm: 2.3.1
    env: PUPPET_GEM_VERSION="~> 4.0" STDLIB_LOG_DEPRECATIONS="false"
    bundler_args: --without system_tests
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.0" STDLIB_LOG_DEPRECATIONS="false"
    bundler_args: --without system_tests
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
    bundler_args: --without system_tests
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0"
    bundler_args: --without system_tests
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
    bundler_args: --without system_tests
spec/spec_helper.rb:
  allow_deprecations: true
