---
".gitlab-ci.yml":
  deploy_to_forge:
    enabled: false
  branches:
    - release
  user: puppet
  secure: ''
  use_litmus: true
  litmus:
    provision_list:
    - ---travis_el
    - travis_deb
    - travis_el7
    - travis_el8
    complex:
    - collection:
        puppet_collection:
        - puppet6
        provision_list:
        - travis_ub_6
  simplecov: true
  notifications:
    slack:
      secure: l/MKqMgGSmyUUVfGyJnNA23atn1komaEvl3GsFz3e4MJsmLW4eOqFbszrcbQafrT3WdClYUmv1GaJT1OJTsXfV5kHL5TUp2Q7R372mtYYlyP13b0AqyDoQX9DyrGpo6oA5NDvQG4ygL1wxEhoqHohAWyjusG9Z5/duiO57K6Ls0=
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
.github/workflows/nightly.yml:
  unmanaged: false
.github/workflows/pr_test.yml:
  unmanaged: false
.github/workflows/auto_release.yml:
  unmanaged: false
.github/workflows/spec.yml:
  checks: 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
  unmanaged: false
.github/workflows/release.yml:
  unmanaged: false
.travis.yml:
  delete: true
Gemfile:
  optional:
    ":development":
    - gem: rspec-retry
      version: '= 0.4.5'
      platforms: ruby
