---
".gitlab-ci.yml":
  delete: true
appveyor.yml:
  delete: true
Gemfile:
  optional:
    ":development":
    - gem: github_changelog_generator
      git: https://github.com/skywinder/github-changelog-generator
      ref: 20ee04ba1234e9e83eb2ffb5056e23d641c7a018
      condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')
    - gem: rspec-retry
      require: false
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
'.travis.yml':
  global_env: 
    - HONEYCOMB_WRITEKEY="7f3c63a70eecc61d635917de46bea4e6",HONEYCOMB_DATASET="litmus tests"
  deploy_to_forge:
    enabled: false
  branches:
    - release
  user: puppet
  secure: ''
  includes:
    - bundler_args:
      env: PLATFORMS=deb_puppet5
      rvm: 2.5.3
      before_script:
        - bundle exec rake 'litmus:provision_list[travis_deb]'
        - bundle exec rake 'litmus:install_agent[puppet5]'
        - bundle exec rake litmus:install_module
      script:
        - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
      stage: acceptance
    - bundler_args:
      env: PLATFORMS=deb_puppet6
      rvm: 2.5.3
      before_script:
        - bundle exec rake 'litmus:provision_list[travis_deb]'
        - bundle exec rake 'litmus:install_agent[puppet6]'
        - bundle exec rake litmus:install_module
      script:
        - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
      stage: acceptance
    - bundler_args:
      env: PLATFORMS=ub_puppet5
      rvm: 2.5.3
      before_script:
        - bundle exec rake 'litmus:provision_list[travis_ub]'
        - bundle exec rake 'litmus:install_agent[puppet5]'
        - bundle exec rake litmus:install_module
      script:
        - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
      stage: acceptance
    - bundler_args:
      env: PLATFORMS=ub_puppet6
      rvm: 2.5.3
      before_script:
        - bundle exec rake 'litmus:provision_list[travis_ub]'
        - bundle exec rake 'litmus:install_agent[puppet6]'
        - bundle exec rake litmus:install_module
      script:
        - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
      stage: acceptance
    - bundler_args:
      env: PLATFORMS=el6_puppet5
      rvm: 2.5.3
      before_script:
        - bundle exec rake 'litmus:provision_list[travis_el6]'
        - bundle exec rake 'litmus:install_agent[puppet5]'
        - bundle exec rake litmus:install_module
      script:
        - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
      stage: acceptance
    - bundler_args:
      env: PLATFORMS=el6_puppet6
      rvm: 2.5.3
      before_script:
        - bundle exec rake 'litmus:provision_list[travis_el6]'
        - bundle exec rake 'litmus:install_agent'
        - bundle exec rake litmus:install_module
      script:
        - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
      stage: acceptance
    - bundler_args:
      env: PLATFORMS=el7_puppet5
      rvm: 2.5.3
      before_script:
        - bundle exec rake 'litmus:provision_list[travis_el7]'
        - bundle exec rake 'litmus:install_agent[puppet5]'
        - bundle exec rake litmus:install_module
      script:
        - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
      stage: acceptance
    - bundler_args:
      env: PLATFORMS=el7_puppet6
      rvm: 2.5.3
      before_script:
        - bundle exec rake 'litmus:provision_list[travis_el7]'
        - bundle exec rake 'litmus:install_agent'
        - bundle exec rake litmus:install_module
      script:
        - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
      stage: acceptance
  simplecov: true

