---
# only run a minimal subset of tests on travis, running all the tests can cause travis to timeout
.travis.yml:
  bundle_args: --without system_tests
  docker_sets:
  - set: docker/ubuntu-14.04
    options:
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=@@SET@@ SPEC_OPTS="--tag docker"
  - set: docker/centos-7
    options:
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=@@SET@@ SPEC_OPTS="--tag docker"
  secure: ""
  branches:
    - release
  extras:
    - env: CHECK=release_checks
      rvm: 2.1.9

Gemfile:
  required:
    ':system_tests':
      - gem: 'puppet-module-posix-system-r#{minor_version}'
        platforms: ruby
      - gem: 'puppet-module-win-system-r#{minor_version}'
        platforms:
          - mswin
          - mingw
          - x64_mingw
      - gem: beaker
        version: '~> 3.13'
        from_env: BEAKER_VERSION
      - gem: beaker-abs
        from_env: BEAKER_ABS_VERSION
        version: '~> 0.1'
      - gem: beaker-pe
      - gem: beaker-hostgenerator
        from_env: BEAKER_HOSTGENERATOR_VERSION
    ':development':
      - gem: puppet-blacksmith
        version: '~> 3.4'
      - gem: beaker-rspec
        from_env: BEAKER_RSPEC_VERSION
      - gem: beaker
        from_env: BEAKER_VERSION
  optional:
    ':system_tests':
      - gem: rspec-retry

Rakefile:
  requires:
    - puppet_blacksmith/rake_tasks

